name = "telegraph-image"
compatibility_date = "2026-04-20"

[[r2_buckets]]
binding = "IMGRS"
bucket_name = "image2"
jurisdiction = ""

[[d1_databases]]
binding = "IMG"
database_name = "image"
database_id = "d3e3501f-1230-481d-88ed-9de7a30493fd"
